I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 273, in script
    python:
  File "renpy/common/00start.rpy", line 277, in <module>
    renpy.call_in_new_context("_main_menu")
  File "game/script.rpy", line 140, in script
    jump dei2
  File "game/script.rpy", line 140, in script
    jump dei2
ScriptError: could not find label 'dei2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 273, in script
    python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 277, in <module>
    renpy.call_in_new_context("_main_menu")
  File "renpy/game.py", line 344, in call_in_new_context
    return renpy.execution.run_context(False)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "game/script.rpy", line 140, in script
    jump dei2
  File "game/script.rpy", line 140, in script
    jump dei2
  File "renpy/ast.py", line 1757, in execute
    rv = renpy.game.script.lookup(target)
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'dei2'.

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
Не смотри наверх. 1.0
Tue Feb  1 00:41:01 2022
